In [1]:
# ==========================================================
# PROJECT SETUP
# ==========================================================

from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd().parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

print(PROJECT_ROOT)

d:\Kavya Shankar_Workspace\Kaggle Projects\Predicting Smartphone Addiction

In [2]:
# ==========================================================
# PROJECT SETUP
# ==========================================================

from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd().parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

print("Project Root:", PROJECT_ROOT)

Project Root: d:\Kavya Shankar_Workspace\Kaggle Projects\Predicting Smartphone Addiction

In [3]:
from src.feature_engineering import engineer_features

print("Feature engineering module imported successfully.")

Feature engineering module imported successfully.

In [4]:
from src.data_loader import load_data

train_df, test_df, sample_submission = load_data()

print("Train Shape :", train_df.shape)
print("Test Shape  :", test_df.shape)
print("Sample Submission Shape :", sample_submission.shape)

Train Shape : (691369, 14)
Test Shape  : (296302, 13)
Sample Submission Shape : (296302, 2)

In [5]:
print(train_df.columns.tolist())
print(test_df.columns.tolist())

['id', 'age', 'daily_screen_time_hours', 'social_media_hours', 'gaming_hours', 'work_study_hours', 'sleep_hours', 'notifications_per_day', 'app_opens_per_day', 'weekend_screen_time', 'gender', 'stress_level', 'academic_work_impact', 'addicted_label']
['id', 'age', 'daily_screen_time_hours', 'social_media_hours', 'gaming_hours', 'work_study_hours', 'sleep_hours', 'notifications_per_day', 'app_opens_per_day', 'weekend_screen_time', 'gender', 'stress_level', 'academic_work_impact']

In [6]:
# ==========================================================
# PHASE 03 | FEATURE ENGINEERING
# ==========================================================

from src.feature_engineering import engineer_features

train_fe = engineer_features(train_df)
test_fe = engineer_features(test_df)

print("Train Shape :", train_fe.shape)
print("Test Shape  :", test_fe.shape)

Train Shape : (691369, 23)
Test Shape  : (296302, 22)

In [7]:
new_features = [
    "total_entertainment_hours",
    "weekend_difference"
]

print(train_fe[new_features].head())

   total_entertainment_hours  weekend_difference
0                       3.42                 NaN
1                        NaN                 NaN
2                        NaN                2.38
3                       2.68                2.24
4                       4.68                2.19

In [8]:
print(train_fe[new_features].describe().T)

                              count      mean       std   min   25%   50%  \
total_entertainment_hours  484281.0  3.930318  1.679299  0.01  2.64  3.82
weekend_difference         517906.0  1.837633  1.766462 -7.91  0.63  1.84

                            75%    max
total_entertainment_hours  5.11  11.29
weekend_difference         3.03  11.49

In [9]:
print(train_fe[new_features].isna().sum())

total_entertainment_hours    207088
weekend_difference           173463
dtype: int64

In [10]:
ratio_features = [
    "entertainment_ratio",
    "social_media_ratio",
    "gaming_ratio",
    "work_study_ratio"
]

train_fe[ratio_features].describe().T

,count,mean,std,min,25%,50%,75%,max
entertainment_ratio,451246.0,0.524056,0.147803,0.003903,0.432498,0.528384,0.623656,0.947047
social_media_ratio,502260.0,0.326852,0.134412,0.000000,0.230927,0.330275,0.417889,0.885321
gaming_ratio,507723.0,0.197116,0.111112,0.000000,0.107394,0.198529,0.273945,0.799511
work_study_ratio,553430.0,0.318544,0.137212,0.000000,0.214209,0.321696,0.412511,0.928218

In [11]:
train_fe[ratio_features].isna().sum()

entertainment_ratio    240123
social_media_ratio     189109
gaming_ratio           183646
work_study_ratio       137939
dtype: int64

In [12]:
train_fe[ratio_features].agg(["min", "max"])

     entertainment_ratio  social_media_ratio  gaming_ratio  work_study_ratio
min             0.003903            0.000000      0.000000          0.000000
max             0.947047            0.885321      0.799511          0.928218

In [13]:
train_fe["leisure_to_work_ratio"].describe()

count    451821.000000
mean          2.319269
std           2.018603
min           0.007421
25%           1.100840
50%           1.649123
75%           2.757085
max          21.083333
Name: leisure_to_work_ratio, dtype: float64

In [14]:
print("Missing:", train_fe["leisure_to_work_ratio"].isna().sum())
print("Infinite:", train_fe["leisure_to_work_ratio"].isin([float("inf"), float("-inf")]).sum())

Missing: 239548
Infinite: 0

In [15]:
print(
    "Missing:",
    train_fe["leisure_to_work_ratio"].isna().sum()
)

print(
    "Infinite:",
    train_fe["leisure_to_work_ratio"]
    .isin([float("inf"), float("-inf")])
    .sum()
)

Missing: 239548
Infinite: 0

In [16]:
train_fe["leisure_to_work_ratio"].describe()

count    451821.000000
mean          2.319269
std           2.018603
min           0.007421
25%           1.100840
50%           1.649123
75%           2.757085
max          21.083333
Name: leisure_to_work_ratio, dtype: float64

In [25]:
engineered_features = [
    "total_entertainment_hours",
    "weekend_difference",
    "entertainment_ratio",
    "social_media_ratio",
    "gaming_ratio",
    "work_study_ratio",
    "leisure_to_work_ratio",
    "screen_time_waking_ratio",
    "non_screen_time",
]

print("Engineered Features:")
for feature in engineered_features:
    print("-", feature)

print("\nTotal:", len(engineered_features))

Engineered Features:
- total_entertainment_hours
- weekend_difference
- entertainment_ratio
- social_media_ratio
- gaming_ratio
- work_study_ratio
- leisure_to_work_ratio
- screen_time_waking_ratio
- non_screen_time

Total: 9

In [26]:
print("Train columns:", train_fe.shape[1])
print("Test columns :", test_fe.shape[1])

print(
    "Target in train:",
    "addicted_label" in train_fe.columns
)

print(
    "Target in test:",
    "addicted_label" in test_fe.columns
)

Train columns: 23
Test columns : 22
Target in train: True
Target in test: False

In [18]:
import pandas as pd
missing_analysis = pd.DataFrame({
    "missing_count": train_df.isna().sum(),
    "missing_rate": train_df.isna().mean(),
})

missing_analysis

                         missing_count  missing_rate
id                                   0      0.000000
age                              28929      0.041843
daily_screen_time_hours          95854      0.138644
social_media_hours              133995      0.193811
gaming_hours                    126821      0.183435
work_study_hours                 51518      0.074516
sleep_hours                      44480      0.064336
notifications_per_day            67584      0.097754
app_opens_per_day                80710      0.116739
weekend_screen_time             112063      0.162089
gender                           29034      0.041995
stress_level                     55148      0.079766
academic_work_impact             44224      0.063966
addicted_label                       0      0.000000

In [ ]:
missing_features = [
    "social_media_hours",
    "gaming_hours",
    "weekend_screen_time",
    "daily_screen_time_hours",
    "app_opens_per_day",
    "notifications_per_day",
]

for feature in missing_features:
    print(f"\n{'=' * 60}")
    print(feature)
    print(train_df.groupby(train_df[feature].isna())["addicted_label"].mean())

============================================================
social_media_hours
social_media_hours
False    0.709427
True     0.709415
Name: addicted_label, dtype: float64

============================================================
gaming_hours
gaming_hours
False    0.709182
True     0.710505
Name: addicted_label, dtype: float64

============================================================
weekend_screen_time
weekend_screen_time
False    0.709187
True     0.710654
Name: addicted_label, dtype: float64

============================================================
daily_screen_time_hours
daily_screen_time_hours
False    0.709122
True     0.711301
Name: addicted_label, dtype: float64

============================================================
app_opens_per_day
app_opens_per_day
False    0.708980
True     0.712787
Name: addicted_label, dtype: float64

============================================================
notifications_per_day
notifications_per_day
False    0.709336
True     0.710242
Name: addicted_label, dtype: float64

In [20]:
categorical_features = [
    "gender",
    "stress_level",
    "academic_work_impact",
]

for feature in categorical_features:
    print(f"\n{'=' * 60}")
    print(feature)
    print(
        train_df.groupby(train_df[feature].isna())["addicted_label"].mean()
    )

============================================================
gender
gender
False    0.709452
True     0.708790
Name: addicted_label, dtype: float64

============================================================
stress_level
stress_level
False    0.709461
True     0.709001
Name: addicted_label, dtype: float64

============================================================
academic_work_impact
academic_work_impact
False    0.709422
True     0.709456
Name: addicted_label, dtype: float64

In [21]:
print(train_fe["screen_time_waking_ratio"].describe())

print(
    "Missing:",
    train_fe["screen_time_waking_ratio"].isna().sum()
)

print(
    "Infinite:",
    train_fe["screen_time_waking_ratio"]
    .isin([float("inf"), float("-inf")])
    .sum()
)

count    559350.000000
mean          0.446800
std           0.163338
min           0.025667
25%           0.315646
50%           0.451197
75%           0.577791
max           0.789141
Name: screen_time_waking_ratio, dtype: float64
Missing: 132019
Infinite: 0

In [22]:
print(
    "Correlation:",
    train_fe["screen_time_waking_ratio"]
    .corr(train_fe["addicted_label"])
)

Correlation: 0.6022706325281635

In [23]:
non_screen_time = (
    24
    - train_df["sleep_hours"]
    - train_df["daily_screen_time_hours"]
)

print(non_screen_time.describe())

print(
    "Correlation:",
    non_screen_time.corr(train_df["addicted_label"])
)

count    559350.000000
mean          9.557445
std           3.018307
min           3.990000
25%           7.210000
50%           9.490000
75%          11.860000
max          18.980000
dtype: float64
Correlation: -0.5682184512487154

In [27]:
# ==========================================================
# PHASE 04 | PREPROCESSING
# STEP 01 | SEPARATE FEATURES AND TARGET
# ==========================================================

X = train_fe.drop(columns=["addicted_label"])
y = train_fe["addicted_label"]

X_test = test_fe.copy()

print("X Shape      :", X.shape)
print("y Shape      :", y.shape)
print("X_test Shape :", X_test.shape)

X Shape      : (691369, 22)
y Shape      : (691369,)
X_test Shape : (296302, 22)

In [28]:
print("Target in X     :", "addicted_label" in X.columns)
print("Target in X_test:", "addicted_label" in X_test.columns)

Target in X     : False
Target in X_test: False